### ISSUE TITLE
plugin fails when running with sshfs

### ISSUE THREAD

**Issue by rodrigogansobarbieri** [dosaboy/hotsos#140]
using sshfs to mount a remote nova-compute / at ~/remote in my VM and trying to run hotsos against it produces the following error:

```
ubuntu@ganso-bastion:~/git/hotsos$ sudo ./hotsos.sh ~/remote/
INFO: analysing sosreport at /home/ubuntu/remote -Traceback (most recent call last):
  File "/home/ubuntu/git/hotsos/plugins/system/main.py", line 5, in <module>
    PluginRunner()()
  File "/home/ubuntu/git/hotsos/core/plugintools.py", line 226, in __call__
    inst()
  File "/home/ubuntu/git/hotsos/plugins/system/pyparts/checks.py", line 114, in __call__
    self.sysctl_checks()
  File "/home/ubuntu/git/hotsos/plugins/system/pyparts/checks.py", line 99, in sysctl_checks
    if value != actuals[key]:
KeyError: 'net.ipv4.neigh.default.gc_thresh1'
 
hotsos:
  version: development
  repo-info: a8f45b7
juju:
  version: 2.9.14
  machine: '21'
  charms:
    - neutron-openvswitch-291
    - nova-compute-334
  units:
    local:
      - neutron-openvswitch-0
      - nova-compute-0
  potential-issues:
    - desc: there is no Juju machined running on this host but it seems there should
        be
      origin: juju.machines
      type: JujuWarning
kernel:
  cpu:
    smt: disabled
  memory-checks: no issues found
```

At first I thought it was because of "analysing sosreport at /home/ubuntu/remote" so I edited hotsos.sh and replaced DATA_ROOT with the path, despite observing that it is pretty much what the code does and the sosreport path message doesn't seem to be relevant, and it gave the same error.

SSHFS works fine and I can access the remote filesystem at ~/remote

**Comment by rodrigogansobarbieri** [comment]
The cause of the error is [0].

After changing that value to the path of the sshfs mount, hotsos ran successfully, however, it ran with a lot of data missing when compared to running in the live system itself, and a lot of data (such as kernel version) was from my VM instead of the nova-compute node.

I believe that is because it is invoking BinCmd in my VM. Right now, I see that the commands such as sysctl_all can either be run as a command in the live system or as a file that its path in this particular case would exist in a sosreport. Therefore there would need to be an alternative to access this data through a file in the system such /run, /proc, etc, which are available in the sshfs mount.

[0] https://github.com/dosaboy/hotsos/blob/a8f45b7a4ffa3bd5a0651a5dbdf5f0d99eb806bb/core/cli_helpers.py#L307

**Comment by rodrigogansobarbieri** [comment]
as a complementary note, setting up sshfs required copying the authorized_keys of the ubuntu user in the nova-compute node to the /root user, because sshfs needs to be run as root. The known_hosts data would also need to be copied, but I did not need to because I tested ssh'ing to it beforehand and it got added to the known_hosts.

**Comment by rodrigogansobarbieri** [comment]
I made the minimum required changes for this to work, and this is the performance result:

running in the host:
real    0m10.293s
user    0m9.104s
sys     0m1.821s

running remotely:
real    1m33.523s
user    0m12.645s
sys	    0m2.931s


Performance is terrible. I guess we will need to find another way to re-using hotsos assets and sharing the code. We can close this bug.
