### ISSUE TITLE
hotsos snap encoding issue

### ISSUE THREAD

**Issue by brettmilford** [dosaboy/hotsos#51]
Running hotsos (snap) against a sosreport with cdk installed happens to trigger this when parsing snap names:

```
Traceback (most recent call last):
  File "/snap/hotsos/160/plugins/kubernetes/01general", line 100, in <module>
    get_snap_info()
  File "/snap/hotsos/160/plugins/kubernetes/01general", line 56, in get_snap_info
    snap_list_all = helpers.get_snap_list_all()
  File "/snap/hotsos/160/plugins/kubernetes/common/helpers.py", line 64, in catch_exception_inner2
    return f(*args, **kwargs)
  File "/snap/hotsos/160/plugins/kubernetes/common/helpers.py", line 218, in get_snap_list_all
    return open(path, 'r').readlines()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1604: ordinal not in range(128)
```

**Comment by brettmilford** [comment]
fixed by bb11584
